"""Editable research coverage, including non-software freelance services."""

# name: (Apple genre, discovery phrases, small product hypothesis)
APPS = {
    "Health & fitness": (6013, ["workout tracker", "meal tracker"], "a focused tracker for one underserved fitness routine"),
    "Productivity": (6007, ["habit tracker", "personal planner"], "a planner for one recurring personal workflow"),
    "Finance": (6015, ["budget planner", "expense tracker"], "a local-first budget tool for a specific household type"),
    "Education": (6017, ["language learning", "exam preparation"], "short practice sessions for one exam or language pair"),
    "Photo & video": (6008, ["photo editor", "video captions"], "one repeatable editing task with a fast export flow"),
    "Utilities": (6002, ["document scanner", "file organizer"], "a simple utility with transparent one-time pricing"),
    "Lifestyle": (6012, ["journal diary", "home organization"], "a private journal for a clearly defined life stage"),
    "Entertainment": (6016, ["entertainment", "party games"], "a lightweight shared entertainment experience"),
    "Games": (6014, ["puzzle game", "casual game"], "a small puzzle with a distinctive mechanic"),
    "Travel": (6003, ["trip planner", "packing list"], "an offline trip helper for a specific traveler type"),
    "Food & drink": (6023, ["recipe organizer", "meal planning"], "meal planning for one dietary constraint"),
    "Shopping": (6024, ["shopping list", "price tracker"], "a reusable purchase comparison or household list tool"),
    "Social & dating": (6005, ["dating", "friend finder"], "a small community around one recurring shared activity"),
    "Music": (6011, ["music practice", "instrument tuner"], "a practice companion for one instrument"),
    "Sports": (6004, ["sports training", "score keeper"], "a scorekeeper or drill planner for one amateur sport"),
    "Weather": (6001, ["weather alerts", "weather forecast"], "weather decisions tailored to one outdoor activity"),
    "Navigation": (6010, ["offline maps", "hiking navigation"], "a focused route or location helper"),
    "Books": (6018, ["reading tracker", "audiobooks"], "a reading companion for a specific reader community"),
    "News": (6009, ["news reader", "local news"], "a paid digest serving one well-defined information need"),
    "Medical": (6020, ["medication reminder", "symptom diary"], "a private reminder or diary without diagnostic claims"),
    "Reference": (6006, ["dictionary", "plant identifier"], "an offline reference tool for one practical hobby"),
    "Business tools for individuals": (6000, ["invoice maker", "resume builder"], "one personal work task with a simple pay-per-use option"),
    "Developer tools": (6026, ["coding practice", "code editor"], "a mobile coding or learning utility for individuals"),
    "Graphics & design": (6027, ["drawing app", "graphic design"], "a template tool for one consumer creative task"),
    "Magazines": (6021, ["magazine reader", "digital magazines"], "a reading utility for a narrow enthusiast audience"),
    "Kids & parenting": (None, ["baby tracker", "parenting routine"], "a shared family routine tracker with minimal data collection"),
    "Pets & hobbies": (None, ["pet care", "garden planner"], "a care schedule for one pet or hobby"),
}

# name: (search terms, proposed sellable starter service, complexity)
FREELANCE = {
    "AI & automation": (["automation", "chatbot", "n8n", "make.com", "llm", "zapier"], "automate one repetitive business workflow", "moderate"),
    "Web development": (["website", "wordpress", "webflow", "react", "frontend", "web development"], "fix or build one conversion-focused web page", "moderate"),
    "Mobile development": (["flutter", "react native", "android", "ios", "mobile app"], "deliver a small mobile feature or prototype", "complex"),
    "E-commerce": (["shopify", "woocommerce", "ecommerce", "e-commerce", "amazon store"], "improve one store's catalog or checkout flow", "moderate"),
    "Data & analytics": (["data analysis", "power bi", "tableau", "dashboard", "excel", "sql", "data science"], "turn a recurring spreadsheet into a decision dashboard", "moderate"),
    "Design & UX": (["figma", "ux", "ui design", "graphic design", "logo", "branding"], "redesign one user journey with a tested prototype", "simple"),
    "Video & animation": (["video edit", "animation", "motion graphics", "reels", "after effects"], "produce a repeatable short-form video package", "moderate"),
    "Writing & translation": (["copywriting", "content writing", "translation", "proofreading", "technical writing"], "deliver a specialized content or translation package", "simple"),
    "SEO & marketing": (["seo", "google ads", "facebook ads", "digital marketing", "email marketing"], "audit and improve one measurable acquisition channel", "moderate"),
    "Social media": (["social media", "community manager", "tiktok", "instagram"], "plan and produce a focused monthly content package", "simple"),
    "Virtual assistance": (["virtual assistant", "data entry", "web research", "administrative", "lead generation"], "handle a clearly scoped research or operations process", "simple"),
    "Accounting & finance": (["bookkeeping", "accounting", "quickbooks", "financial model", "tax preparation"], "reconcile and report one small business's books", "moderate"),
    "Engineering & CAD": (["cad", "solidworks", "autocad", "mechanical", "electrical", "pcb"], "prepare one manufacturable design or drawing package", "complex"),
    "Architecture & interiors": (["architecture", "interior design", "revit", "floor plan", "3d rendering"], "produce a room design or rendering package", "complex"),
    "Cybersecurity & IT": (["cybersecurity", "security audit", "penetration", "system admin", "network admin"], "deliver a scoped defensive configuration review", "complex"),
    "Cloud & DevOps": (["devops", "aws", "docker", "kubernetes", "cloud", "ci/cd"], "set up a reliable deployment and monitoring workflow", "complex"),
    "QA & testing": (["testing", "qa", "selenium", "playwright", "test automation"], "test a critical customer flow and document defects", "moderate"),
    "Sales & support": (["customer support", "sales", "appointment setting", "telemarketing", "crm"], "manage a measurable support or sales operations task", "simple"),
    "Audio & voice": (["voice over", "voiceover", "audio", "podcast", "music production"], "deliver an edited podcast or voice recording package", "moderate"),
    "Research & consulting": (["market research", "business plan", "consulting", "legal research", "grant"], "produce a sourced decision brief for one business question", "moderate"),
    "Geospatial": (["gis", "geospatial", "qgis", "arcgis", "remote sensing", "cartography"], "deliver one mapping or spatial analysis task", "moderate"),
    "Other services": ([], "validate a specific service against the linked client briefs", "unknown"),
}
